### PR TITLE
Speculative PR

### PR DESCRIPTION
**Pull request by russelldb**
This is really a speculative PR. Not sure if it is the right thing to do, but in a "works for me" way, it updates rebar_riak_core so that I am able to run

    make install
    cd ../
    mkdir myapp
    ./rebar create template=riak_core appid=myapp
    make rel
    rel/myapp/bin/myapp console

and it works.

Not saying "hey merge this" saying "is this enough to make rebar_riak_core usable again?"

### CODE REVIEW

**Comment by andrewjstone** [comment]
After taking a closer look and actually running this, it appears it works because it checks out `develop` which doesn't actually have the clique code in riak_core. 

However, when I switch the riak_core branch to 2.0, it still works and handles things properly. So it's ready for that merge from 2.0 to develop, Cli code still works also.

```
(myapp@127.0.0.1)1> riak_core_console:command(["riak-admin", "show", "transfer_limit"]).
+---------------+--------------+
|     node      |transfer_limit|
+---------------+--------------+
|myapp@127.0.0.1|      2       |
+---------------+--------------+

```

**Comment by andrewjstone** [comment]
:+1:  c313bfc

Nice work @russelldb

**Comment by russelldb** [comment]
So it doesn't use 2.0 by default? Hmm, it was meant to.

**Comment by russelldb** [comment]
Pushed change to use `riak_core/2.0` by default.

**Comment by andrewjstone** [comment]
It works. +1.

**Comment by russelldb** [comment]
Fanks mang!

**Pull request merged**
